### ISSUE TITLE
Provide comparison/benchmarks against `indent-o-matic`

### ISSUE THREAD

**Issue by krishnakumarg1984** [NMAC427/guess-indent.nvim#4]
Thank you for making this plugin. Are there advantages/USPs of using this over [`indent-o-matic`](https://github.com/Darazaki/indent-o-matic), another fairly new lua plugin?

Perhaps you could provide an explanation and/or benchmarks?

**Comment by Darazaki** [comment]
Hi, I'm `indent-o-matic`'s creator! I've already provided an explanation [here](https://github.com/Darazaki/indent-o-matic/issues/12#issuecomment-1126820839) so feel free to correct me if I got anything wrong

Also NMAC427, is it ok if I add `guess-indent.nvim` to [`indent-o-matic`'s list of alternatives](https://github.com/Darazaki/indent-o-matic#alternatives) with something like:

> guess-indent.nvim by Nicolas Camenisch: Smarter algorithm, configuration similar to indent-o-matic

(Just to make it distinct from crazy8.nvim's description)

**Comment by NMAC427** [comment]
I'm going to close this issue, because the explanation in the [`indent-o-matic` issue](https://github.com/Darazaki/indent-o-matic/issues/12) is perfect.

**Comment by NMAC427** [comment]
> Also NMAC427, is it ok if I add `guess-indent.nvim` to [`indent-o-matic`'s list of alternatives](https://github.com/Darazaki/indent-o-matic#alternatives) with something like:

Definetly! Please feel free to add the link.

**Comment by krishnakumarg1984** [comment]
This is absolutely comprehensive response from both the plugin authors. Thank you so much.

May I suggest pinning this issue and provide a link in the README (under a section titled alternatives/benchmarks or something equivalent) for each of the two plugins?
